### PR TITLE
Add meta theme color

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR adds missing `<meta name="theme-color" content="#141216"/>` as suggested by Lighthouse.

Issue: https://github.com/GoogleChrome/kino/issues/142

### CODE REVIEW

**Review by dero — APPROVED** [review]
This looks good if we want to just appease Lighthouse, approving. 👍 

There are, however, some considerations around the dark mode. Right now the dark mode is applied when:

1. It's enabled in app settings.
2. It's enabled in the OS (trumps app settings).

While we could do something like this to change the `theme-color` when dark mode is enabled in the OS:

```html
<meta name="theme-color" content="#fff"/>
<meta name="theme-color" content="#141216" media="(prefers-color-scheme: dark)" />
```

... we would then still need to dynamically change the former value when dark mode is enabled in the app using settings.

So it seems we might want to set the `theme-color` dynamically during app initialization based on the `--background` CSS property:

```js
// Not tested, but something along these lines should work.
const metaThemeColorElement = document.querySelector('meta[name="theme-color"]');
const currentThemeColor = getComputedStyle(document.documentElement).getPropertyValue('--background').trim()

if (currentThemeColor) {
  metaThemeColorElement.setAttribute('content', currentThemeColor);
}
```

**Comment by derekherman** [comment]
It would make sense to fix it for both light and dark mode.

**Comment by beaufortfrancois** [comment]
Good catch indeed! I've handled light, dark and forced dark mode in latest commits. Please have a look.

**Review by dero — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
