### PR TITLE
Add maskable icons to manifest

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR adds missing maskable icons to the web app manifest as suggested by Lighthouse.

Issue: https://github.com/GoogleChrome/kino/issues/142

### CODE REVIEW

**Review by dero — APPROVED** [review]
These icons look good. Tested in Chrome DevTools.

image

(But I do find it a bit funny that in order to avoid devices adding padding and white background to our icons, we... add padding and white background to our icons. 😉)

**Comment by beaufortfrancois** [comment]
At least we control the padding ;)
See https://web.dev/maskable-icon/

**Comment by derekherman** [comment]
The padding I understand, but why the white background?

**Comment by beaufortfrancois** [comment]
Which other color would you use? White seems appropriate to me.
I don't see how no color would match the triangle shape of the icon as well.

**Comment by derekherman** [comment]
My understanding is that the background should be completely filled or have none as there are different icon shapes like square, teardrop, round rectangle, and squircle that the icon can be shown in. If the background is a white circle but the theme color is dark wouldn't the icon be partially white and then outside of the circle it would be the theme color?

**Comment by dero** [comment]
@derekherman The icon background [is completely filled](https://github.com/GoogleChrome/kino/blob/54cd63653cca0eba25de899f6497a578f0e93e05/public/images/maskable-icon-128x128.png). DevTools only previews the icon as a circle, because that is the maximum amount of crop that _can_ be applied.

**Comment by beaufortfrancois** [comment]
FYI I used https://maskable.app/ to create this maskable icon for kinoweb.dev.

**Comment by derekherman** [comment]
I see. Shouldn’t the background color be the theme color of the app then? It looks best on that dark background.

**Comment by beaufortfrancois** [comment]
I'm not sure I like the dark background. Note that Google apps all use white background.

image
image
image

**Comment by derekherman** [comment]
We can leave it with the white background.

**Pull request merged**
